config/routes.rb
WBlog::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy]
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/controllers/blogs_controller.rb
# encoding : utf-8
class BlogsController < ApplicationController

  def index
    @newest = Post.order(created_at: :desc).first
    @recent = Post.order(created_at: :desc).to_a[1..3]
    respond_to do |format|
      format.html
      format.json
    end
  end

  def rss
    @posts = Post.all.order(:created_at => :desc).limit(10)
    render :layout=>false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end

  def show
    cookies[:cable_id] = SecureRandom.uuid
    @post = Post.find(params[:id])
    @post.visited
    @prev = Post.where('created_at < ?', @post.created_at).order(created_at: :desc).first
    @next = Post.where('created_at > ?', @post.created_at).order(created_at: :asc).first
    @comments = @post.comments.order(created_at: :desc)
    @likes_count = @post.likes.count
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
    @post = Post.find( params[:id] )
    redirect_to edit_admin_post_path(@post)
  end
end

app/views/blogs/_comment.html.erb
<div class="row">
  <div class="small-12 large-9 large-centered columns">
    <%= form_for Comment.new, url: blog_comments_path(@post), remote: true do |f| %>
      <div class="row">
        <div class="small-12 large-12 columns">
          <%= f.text_area :content, placeholder: t('comment_placeholder.content') %>
        </div>
      </div>

      <div class="row">
        <div class="small-12 large-6 columns">
          <%= f.text_field :name, value: cookies[:name], placeholder: t('comment_placeholder.name') %>
          <%= f.text_field :email, value: cookies[:email], placeholder: t('comment_placeholder.email') %>
      </div>
    </div>

    <button class="button comment-submit" type='submit' data-disable-with="<%= t('comment_placeholder.submitting') %>"><%= t('comment_placeholder.submit') %></button>

    <div class="alert callout" id="alert-container">
      <span class="text"></span>
      <button class="close-button" type="button">
        <span>&times;</span>
      </button>
    </div>
  <% end %>

  <%= render partial: 'comments/comment_content', locals: { comments: comments } %>

  </div>
</div>

app/views/blogs/_post.html.erb
<%= render partial: 'post_head', locals: { post: post } %>

<div class="content markdown">
  <%= post.content_html.html_safe %>
</div>

<p class="ptag published-at">
  <%= t('announce_at') %>
  <span>
    <%= format_time(post.created_at) %>
  </span>
</p>

<%= render 'common/copyright' %>

<hr class="blog-over" />
<p>
  <button class="button like-button" data-url="<%= blog_likes_path(post) %>" type="button">
<span class="count"><%= @likes_count %></span>
<span>Like</span>
</button><div class="qrcode">
<a href="#" id="qrcode-link">
<i class="fi-link">
</i><%= t('qr_code') %>

</a></div><div class="social-share">
<div class="qrcode-wrapper">
<%= render partial: "qrcode", locals: { str: blog_url(post) } %>
</div></div></p>

app/views/blogs/_post_head.html.erb
<h2 class="blog-title"><%= post.title %></h2>
<p class="ptag">
<span>
<i class="fi-pricetag-multiple">
</i></span><span><%= post.labels_content %></span>
</p>

app/views/blogs/_qrcode.html.erb
<div class="qrcode-image">
<div<% _slim_codeattributes1 = str; if _slim_codeattributes1; if _slim_codeattributes1 == true %> data-url=""<% else %> data-url="<%= _slim_codeattributes1 %>"<% end; end %> id="image-tag">
</div><p><%= t('qrcodetips') %></p>
</div>

app/views/blogs/index.html.erb
<% if ENV['INTRODUCE'].present?
content_for(:meta) do
 %><meta content="<%= ENV['INTRODUCE'].dup.force_encoding('UTF-8') %>" name="description" />
<% end; end; content_for(:title) do
 %><%= t('title.home') %>
<% end %><div class="row">
<div class="small-12 large-10 columns">
<% unless @newest
 %><%= render 'common/no_blog_here' %>
<% else
 %><%= render partial: 'post_head', locals: { post: @newest } %>
<div class="content markdown">
<%= @newest.sub_content.html_safe %>

<%= link_to t('home.read'), blog_path(@newest), class: 'read-more' %>
<p class="published-at"><%= t('home.created_at') %> <%= format_time(@newest.created_at) %>
</p>
</div><% if @recent.present?
 %><h4 class="recent-title"><%= t('home.recent') %></h4>
<ul class="recent-content">
<% @recent.each do |re|
 %><li><%= link_to re.title,blog_path(re) %>

</li><% end %></ul><% end; end %></div><div class="large-2 columns self-introduce self-introduce-index">

<%= render 'common/welcome' %>
</div></div>

app/views/blogs/show.html.erb
<% content_for(:meta) do %>
  <meta name="description" content=<%= @post.meta_content %>>
  <meta name="keywords" content=<%= @post.labels_content %>>
<% end %>

<% content_for(:title) do %>
  <%= @post.title %>
<% end %>

<div class="row blog-wrapper#blog-show-page" data-url="<%= refresh_blog_comments_path(@post) %>" data-post_id="<%= @post.id %>">
<div class="small-12 large-9 large-centered columns">
<%= render partial: "post", :locals=> { post: @post } %>
</div></div><div class="comment-field">
<%= render partial: 'comment', locals: { comments: @comments, post: @post } %>
<p>
</p><div class="row">
<div class="small-12 large-9 large-centered columns">
<% if @prev
_slim_controls1 = link_to blog_path(@prev), class: 'prev' do
 %><i class="fi-arrow-left">
</i>Prev
<% end %><%= _slim_controls1 %><% end; if @next
_slim_controls2 = link_to blog_path(@next), class: 'next' do
 %>Next
<i class="fi-arrow-right">
</i><% end %><%= _slim_controls2 %><% end %></div></div></div>