config/routes.rb
WBlog::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy]
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/views/common/_copyright.en.html.erb
<p class="copyright published-at ptag">
© Creative Commons - ShareAlike - NonCommercial - Attribution
</p>

app/views/common/_copyright.html.erb
<p class="copyright published-at ptag">
@先傑網管組 
</p>

app/views/common/_no_blog_here.en.html.erb
<h2 class="blog-title"><%= t('home.no_blog_here') %></h2>
<p>
No post here, please visit
<%= link_to ' Manage Post ', new_admin_post_path %>
to create the first post.
</p>

app/views/common/_no_blog_here.html.erb
<h2 class="blog-title"><%= t('home.no_blog_here') %></h2>
<p>
這裡還沒有日誌，請訪問
<%= link_to '《管理介面》', new_admin_post_path %>
來新增第一篇日誌
</p>

app/views/common/_welcome.en.html.erb
<h4>WELCOME</h4>
<p>I'm Li Yafei, WinDy is my English name.
</p>
<h4>ABOUT</h4>
<ul class="aboutme-index">
<li>
<span>Industry:</span>
<span>Web Development, Startups, Life</span>
</li><li>
<span>Location:</span>
<span>Nan Shan District, ShenZhen, China</span>
</li><li>
<span>More:</span>
<span>
<%= ::Temple::Utils.escape_html((link_to 'About Me', about_path)) %>
</span></li></ul>

app/views/common/_welcome.html.erb
<h4>先傑網管組</h4>
<p>林韋仲 0933-679024</p>
<p>蘇介吾 0921-380997</p>
<p>鄭　川 0929-630120</p>
<p>林志輝 0919-468444</p>

app/views/common/_welcome_new_year.html.erb
<% if (1.days.from_now).strftime('%-m-%-d') =~ /^1-[123]$/
 %><div class="new-year">
<div class="callout primary" data-closable="">
我的朋友, 祝你元旦快乐
<button class="close-button" data-close="" type="button">&times;</button>
</div></div><% end %>