config/routes.rb
WBlog::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create] do
      collection do
        get :refresh
      end
    end
    resources :likes, only: [:index, :create, :destroy]
  end


  resources :archives
  resources :subscribes, only: [:index, :new, :create]

  resources :unsubscribes, only: [:index, :new, :create]
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'

  namespace :admin do
    resources :posts, except: [:show] do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    resources :subscribes, only: [:index] do
      member do
        post :enable
        post :disable
      end
    end
    root 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'

  root 'blogs#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/_footer.html.erb
<div class="row">
<div class="small-12 columns">
<div class="footer">
<div>
<span class="link"><%= ENV['SITE_ADDRESS'] %>
</span><span class="time"><%= ENV['SITE_YEAR'] %>
</span></div></div></div></div>

<script>
$(function() {
  $(".alert").fadeOut(3000)
  $(".success").fadeOut(3000)
})
</script>

app/views/layouts/admin.html.erb
<html>
<head>
  <meta charset="utf-8" />
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <title>Admin Page for <%= ENV['SITE_NAME'] %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="title-bar" data-hide-for="medium" data-responsive-toggle="example-menu">
    <button class="menu-icon" data-toggle="" type="button"></button>
    <div class="title-bar-title">Menu</div>
  </div>

  <div class="top-bar" id="dashboard-topbar">
    <div class="top-bar-left">
      <ul class="menu">
        <li><%= link_to "後台 - #{ENV['SITE_NAME']}", admin_root_path %></li>
        <li><%= link_to t('admin.new_post'), new_admin_post_path %></li>
        <li><%= link_to t('admin.posts'), admin_posts_path %></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><%= link_to t('admin.back'), root_path %></li>
        <% if admin_username %>
          <li><%= link_to admin_username + ' [ ' + t('admin.logout') + ' ]', admin_session_path(1), method: 'DELETE' %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, :class => 'callout success') %>
  <% end %>

  <div class="admin-main-field" ng-app="app">
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>

</body>
</html>

app/views/layouts/application.html.erb
<html>
<head>
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0" name="viewport" />
<% if content_for?(:meta) %>
  <%= yield(:meta) %>
<% end %>
<title>
  <%= content_for?(:title) ? yield(:title) + " | #{ENV['SITE_NAME']}" : ENV['SITE_NAME'] %>
</title>
<%= stylesheet_link_tag "application", 'data-turbolinks-track' => "reload" %>
<%= favicon_link_tag 'favicon.png', type: 'image/png' %>
<%= javascript_include_tag "application", 'data-turbolinks-track' => "reload", 'defer' => true %>
<%= javascript_include_tag Ckeditor.cdn_url %>
<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>
</head>

<body data-whatinput="mouse">

  <% if content_for?(:main) %>

    <%= yield(:main) %>

  <% else %>

    <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper="">
        <div class="off-canvas position-left" data-off-canvas="" id="offCanvas">
          <ul class="vertical menu">
            <li><label>Menu</label></li>
            <li><%= link_to "<i class='fi-home'></i>#{t('head.home')}", root_path %></li>
            <li><%= link_to "<i class='fi-align-justify'></i>#{t('head.timeline')}", archives_path %></li>
            <li><%= link_to "<i class='fi-torso'></i>#{t('head.admin')}", admin_root_path%></li>
          </ul>
        </div>

        <div class="off-canvas-content" data-off-canvas-content="">
          <div class="title-bar hide-for-medium my-topbar">
            <div class="title-bar-left">
              <button class="menu-icon" data-open="offCanvas" type="button"></button>
              <span class="title-bar-title"><%= link_to ENV['SITE_NAME'], root_path %></span>
            </div>
          </div>

          <div class="top-bar show-for-medium my-topbar">
            <div class="top-bar-left">
              <ul class="dropdown menu" data-dropdown-menu="">
                <li><%= link_to ENV['SITE_NAME'], root_path, class: 'title' %></li>
              </ul>
            </div>
            <div class="top-bar-right">
              <ul class="dropdown menu" data-dropdown-menu="">
                <li><%= link_to t('head.home'), root_path %></li>
                <li><%= link_to t('head.timeline'), archives_path %></li>
                <li><%= link_to t('head.admin'), admin_root_path %></li>
                <li><%= link_to "<span><i class='fi-magnifying-glass'></i></span>".html_safe, archives_path %></li>
              </ul>
            </div>
          </div>

          <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, :class => 'callout success') %>
          <% end %>

          <%= render 'common/welcome_new_year' %>

        <%= yield %>

        <%= render "layouts/footer" %>

      </div>
    </div>
  </div>

<% end %>

</body>
</html>